name: example

environment:  
  sdk: ">=2.0.0 <3.0.0" 
  
dependencies: 
  constructor_inherit:  
    path: ../constructor_inherit/
  built_value: '>=5.5.5 <7.0.0'
  meta_types: ^0.1.0
  quiver: ^2.0.1 
 
dev_dependencies:
  build_runner: ^1.2.8
  built_value_generator: ^6.3.2
  meta_types_generator:
    path: ../../dart_meta_types/meta_types_generator
  # meta_types_generator: ^0.1.0
  constructor_inherit_generator:
    path: ../constructor_inherit_generator/    