name: value_t_generator
description: Generates code to create a class that properly inherits and implements all the readonly fields in the hierarchy creating a construtor and a copyWith method
version: 1.0.0
author: Adrian
# homepage: https://github.com/...
 
environment:  
  sdk: ">=2.0.0 <3.0.0" 
  
dependencies:  
  build: ^1.1.1
  source_gen: 0.9.4+1
  value_t:    
    path: ../value_t/  
  quiver: ^2.0.1 
  # dartz: ^0.8.3 
  # adi_helpers:   
  #   # git: git@bitbucket.org/twistedinferno/adi_helpers.git
  #   path: ../../adi_helpers/
      
dev_dependencies:  
  # build_test: ^0.10.0  
  build_runner: ^1.0.0
  test: ^1.0.0
  