name: constructor_inherit
description: Inherits the constructor of its superclasses
version: 1.0.0
author: Adrian
 
environment:  
  sdk: ">=2.0.0 <3.0.0" 

dependencies: 

dev_dependencies:  
  test: 1.3.4