targets:
  $default:
    builders:
      constructor_inherit_generator|constructor_inherit:
        enabled: true
 
builders:
  constructor_inherit:
    target: ":constructor_inherit_generator"
    import: "package:constructor_inherit_generator/builder.dart"
    builder_factories: ["constructorInheritBuilder"]
    build_extensions: {".dart": [".x.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
